[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true
background = false                              # Needed for long-running jobs!
on_change_strategy = "kill_then_restart"        # Needed for long-running jobs!
watch = ["templates", "content"]
