services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cscoursework
      POSTGRES_PASSWORD: RomanMoisieiev
      POSTGRES_DB: app

  backend:
    build: .
    ports:
      - 8080:3000
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./Cargo.toml
